### ISSUE TITLE
eisenstein_hu_nowiggle_variants.py fails... 

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/cosmoprimo#3]
This line 
https://github.com/cosmodesi/cosmoprimo/blob/43c3fcd80e0fe341368981a93f5b735dfe2aa273/cosmoprimo/eisenstein_hu_nowiggle_variants.py#L99
gives me:
AttributeError: attribute 'shape' of 'numpy.generic' objects is not writable
This (error) looks very reasonable to me, and Googling showed up almost nothing (understandably to me because I would never think to do this), so I didn't look into the possibility that it was the fault of my input (which had been working with non-variant version)... but tell me if you think "this should be fine, it must be your input"...

**Comment by adematti** [comment]
ok, I will probably switch to reshape(), but still, I'm interested in the inputs and their type (even, e.g. `np.asarray(np.nan).shape = (1,)` works fine)
(setting .shape instead of calling reshape() ensures no copy of the array is made)

**Comment by pmcdonal** [comment]
It's when I just plug a number, <class 'numpy.float64'>, into the interpolator. An array works... I see in that function you say k should be "array_like" so no surprise at that point and I can fix... although counter-intuitive for an interpolator. (I guess I don't understand numpy enough to have any idea what this means "behind the scenes")

**Comment by adematti** [comment]
ok, thanks! a0d466418f6f5af80d446627109ce11bfb46f8b5 should fix this
