### ISSUE TITLE
theta_MC

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/cosmoprimo#4]
For historical reasons, it would be nice to have easy access to camb's theta_MC, i.e., the thing I hack my way into with:
cosmo.engine.th.cosmomc_theta()

**Comment by adematti** [comment]
Hi,
This should be added by 20073581579bbce91e0870bd506c89110b924436
>>> from cosmoprimo.fiducial import DESI
>>> cosmo = DESI(engine='camb')
>>> cosmo.theta_cosmomc
0.010409292350756895

**Comment by pmcdonal** [comment]
Thanks!
